import { User } from "./user.model";

export const users: Array<User> = [
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://image.freepik.com/free-vector/lion-cool-retro-eyeglasses_68946-257.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://image.freepik.com/free-vector/lion-cool-retro-eyeglasses_68946-257.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://image.freepik.com/free-vector/cartoon-cool-polar-bear_10308-163.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://www.thespruce.com/thmb/zVau4bcJNP9EOF-UhFDiXiERR70=/3000x2000/filters:fill(auto,1)/UNDERSTANDING_WARMCOOL_HERO_-f67c29cadacd4301b8dd3f2056cd39cf.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
  {
    name: 'Inga Lisa Bengtsson',
    date: '1925 - 18/02/2021',
    place: 'Landskrona',
    thumbnail: 'https://minnessidor.fonus.se/assets/common/img/default_profile_picture.jpg',
    isHasDeadNotice: false,
    isHasMemorialPage: true,
    isHasDonate: false,
    isHasFlowerShop: true,
  },
];
